"""
Project Export Service - Generates ZIP files with project data
"""

import json
import logging
from datetime import datetime
from io import BytesIO
from zipfile import ZipFile, ZIP_DEFLATED
from typing import Dict, Any, List

logger = logging.getLogger(__name__)


class ProjectExportService:
    """Service for exporting projects as ZIP files."""
    
    @staticmethod
    def generate_readme(project: Dict[str, Any], tasks: List[Dict[str, Any]]) -> str:
        """Generate README.md content."""
        name = project.get('name', 'Project')
        description = project.get('description', '')
        status = project.get('status', 'unknown')
        selected_agents = project.get('selected_agents', [])
        
        readme = f"""# {name}

## Description
{description}

## Status
{status.capitalize()}

## Agents ({len(selected_agents)})
"""
        for idx, agent in enumerate(selected_agents, 1):
            readme += f"{idx}. {agent}\n"
        
        readme += f"\n## Tasks ({len(tasks)})\n"
        for idx, task in enumerate(tasks, 1):
            readme += f"{idx}. {task.get('name')} - {task.get('status')}\n"
        
        readme += "\n---\nGenerated by AI Agent Project Studio\n"
        return readme
    
    @staticmethod
    def _serialize_datetime(obj):
        """Convert datetime objects to ISO format strings."""
        if isinstance(obj, datetime):
            return obj.isoformat()
        raise TypeError(f"Object of type {type(obj)} is not JSON serializable")
    
    @staticmethod
    async def export_project_as_zip(
        project: Dict[str, Any],
        tasks: List[Dict[str, Any]]
    ) -> BytesIO:
        """Export project as ZIP file."""
        logger.info(f"Exporting project: {project.get('name')}")
        
        zip_buffer = BytesIO()
        
        with ZipFile(zip_buffer, 'w', ZIP_DEFLATED) as zip_file:
            # Add README
            readme = ProjectExportService.generate_readme(project, tasks)
            zip_file.writestr('README.md', readme)
            
            # Add project.json (with datetime serialization)
            zip_file.writestr('project.json', json.dumps(project, indent=2, default=ProjectExportService._serialize_datetime))
            
            # Add tasks.json (with datetime serialization)
            tasks_data = {
                "total_tasks": len(tasks),
                "tasks": tasks
            }
            zip_file.writestr('tasks.json', json.dumps(tasks_data, indent=2, default=ProjectExportService._serialize_datetime))
            
            # Add task outputs and extract artifacts
            for idx, task in enumerate(tasks):
                if task.get('output'):
                    # Save task output as JSON
                    filename = f"outputs/task_{idx+1}_{task.get('agent_id', 'unknown')}.json"
                    output_data = {
                        "task_name": task.get('name'),
                        "agent_id": task.get('agent_id'),
                        "status": task.get('status'),
                        "output": task.get('output'),
                        "result": task.get('result')
                    }
                    zip_file.writestr(filename, json.dumps(output_data, indent=2, default=ProjectExportService._serialize_datetime))
                    
                    # Extract artifacts (generated code files)
                    task_output = task.get('output', {})
                    artifacts = task_output.get('artifacts', [])
                    
                    for artifact in artifacts:
                        artifact_path = artifact.get('path', '')
                        artifact_content = artifact.get('content', '')
                        
                        if artifact_path and artifact_content:
                            # Add artifact to generated_code directory
                            artifact_filename = f"generated_code/{artifact_path}"
                            zip_file.writestr(artifact_filename, artifact_content)
                            logger.info(f"Added artifact to ZIP: {artifact_filename}")
        
        zip_buffer.seek(0)
        logger.info("ZIP export completed")
        return zip_buffer

# Made with Bob
