import React, { useState, useEffect } from 'react';
import JSZip from 'jszip';
import {
  getGeminiHealth,
  analyzeProject as analyzeProjectAPI,
  createProject,
  executeProject,
  getProjectOutput
} from '../services/api';

interface Requirements {
  needsDatabase: boolean;
  needsAuth: boolean;
  needsPayment: boolean;
  needsFAQ: boolean;
}

interface AgentSuggestion {
  agent_id: string;
  agent_name: string;
  reason: string;
  estimated_tokens: number;
}

interface AnalysisResult {
  suggested_agents: AgentSuggestion[];
  total_estimated_tokens: number;
  total_estimated_cost: number;
  analysis: string;
}

export function NewHomePage() {
  // State
  const [geminiAvailable, setGeminiAvailable] = useState(false);
  const [description, setDescription] = useState('');
  const [requirements, setRequirements] = useState<Requirements>({
    needsDatabase: false,
    needsAuth: false,
    needsPayment: false,
    needsFAQ: false,
  });
  
  // Analysis state
  const [analyzing, setAnalyzing] = useState(false);
  const [analysisResult, setAnalysisResult] = useState<AnalysisResult | null>(null);
  
  // Project creation state
  const [creating, setCreating] = useState(false);
  const [projectId, setProjectId] = useState<string | null>(null);
  const [downloadUrl, setDownloadUrl] = useState<string | null>(null);
  
  // Error state
  const [error, setError] = useState<string | null>(null);

  // Check Gemini availability on mount
  useEffect(() => {
    checkGeminiStatus();
  }, []);

  const checkGeminiStatus = async () => {
    try {
      const health = await getGeminiHealth();
      setGeminiAvailable(health.gemini_available);
    } catch (err) {
      console.error('Failed to check Gemini status:', err);
      setGeminiAvailable(false);
    }
  };

  const handleAnalyze = async () => {
    if (!description.trim()) {
      setError('Please enter a project description');
      return;
    }

    setAnalyzing(true);
    setError(null);
    setAnalysisResult(null);

    try {
      const response = await analyzeProjectAPI({
        description,
        requirements,
      });

      if (response.success) {
        setAnalysisResult({
          suggested_agents: response.suggested_agents,
          total_estimated_tokens: response.total_estimated_tokens,
          total_estimated_cost: response.total_estimated_cost,
          analysis: response.analysis,
        });
      } else {
        setError(response.error || 'Analysis failed');
      }
    } catch (err: any) {
      setError(err.message || 'Failed to analyze project');
    } finally {
      setAnalyzing(false);
    }
  };

  const handleCreateProject = async () => {
    if (!analysisResult) return;

    setCreating(true);
    setError(null);

    try {
      // Step 1: Create project
      const projectResponse = await createProject({
        name: description.substring(0, 50),
        description,
        requirements,
        user_id: 'default_user',
      });

      const newProjectId = projectResponse.project_id;
      setProjectId(newProjectId);

      // Step 2: Execute project
      await executeProject(newProjectId);

      // Step 3: Get output and create ZIP file
      const output = await getProjectOutput(newProjectId);
      
      // Create ZIP file with JSZip
      const zip = new JSZip();
      
      // Add all generated files to the ZIP
      if (output.generated_files) {
        for (const [filePath, fileContent] of Object.entries(output.generated_files)) {
          zip.file(filePath, fileContent);
        }
      }
      
      // Add a README with project information
      const readme = `# ${output.project_name}

${output.project_description}

## Project Information
- **Status**: ${output.project_status}
- **Total Tasks**: ${output.total_tasks}
- **Total Files Generated**: ${output.total_files}
- **Total Agents Used**: ${output.total_agents}

## Generated Files
${Object.keys(output.generated_files || {}).map(file => `- ${file}`).join('\n')}

## Agents Used
${output.agent_outputs?.map((agent: any) =>
  `- **${agent.agent_name}** (${agent.agent_id}): ${agent.content || 'No description'}`
).join('\n') || 'No agents'}

---
Generated by BOB Orchestrator with Gemini AI
`;
      zip.file('README.md', readme);
      
      // Generate the ZIP blob
      const blob = await zip.generateAsync({ type: 'blob' });
      const url = URL.createObjectURL(blob);
      setDownloadUrl(url);

    } catch (err: any) {
      setError(err.message || 'Failed to create project');
    } finally {
      setCreating(false);
    }
  };

  const handleDownload = () => {
    if (!downloadUrl) return;
    
    const a = document.createElement('a');
    a.href = downloadUrl;
    a.download = `project-${projectId}.json`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
  };

  const handleReset = () => {
    setDescription('');
    setRequirements({
      needsDatabase: false,
      needsAuth: false,
      needsPayment: false,
      needsFAQ: false,
    });
    setAnalysisResult(null);
    setProjectId(null);
    setDownloadUrl(null);
    setError(null);
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-purple-50 via-blue-50 to-indigo-100">
      <div className="container mx-auto px-4 py-8 max-w-4xl">
        {/* Header */}
        <header className="text-center mb-12">
          <h1 className="text-5xl font-bold text-gray-900 mb-4">
            🤖 BOB AI Code Generator
          </h1>
          <p className="text-xl text-gray-600 mb-4">
            Powered by Gemini AI - Describe your project and get instant code
          </p>
          
          {/* Status Badge */}
          <div className="flex justify-center gap-3">
            <span className={`px-4 py-2 rounded-full text-sm font-semibold ${
              geminiAvailable 
                ? 'bg-green-100 text-green-800' 
                : 'bg-red-100 text-red-800'
            }`}>
              {geminiAvailable ? '✓ Gemini Ready' : '✗ Gemini Unavailable'}
            </span>
          </div>
        </header>

        {/* Main Content */}
        <div className="bg-white rounded-2xl shadow-2xl p-8">
          {/* Step 1: Project Description */}
          {!analysisResult && (
            <div className="space-y-6">
              <div>
                <label className="block text-lg font-semibold text-gray-900 mb-3">
                  📝 What do you want to build?
                </label>
                <textarea
                  value={description}
                  onChange={(e) => setDescription(e.target.value)}
                  placeholder="Example: Create a blog website with user authentication and comments..."
                  className="w-full h-32 px-4 py-3 border-2 border-gray-300 rounded-lg focus:border-purple-500 focus:ring-2 focus:ring-purple-200 transition-all resize-none"
                  disabled={analyzing}
                />
              </div>

              {/* Requirements Checkboxes */}
              <div>
                <label className="block text-lg font-semibold text-gray-900 mb-3">
                  ⚙️ Project Requirements
                </label>
                <div className="grid grid-cols-2 gap-4">
                  {Object.entries(requirements).map(([key, value]) => (
                    <label key={key} className="flex items-center space-x-3 cursor-pointer">
                      <input
                        type="checkbox"
                        checked={value}
                        onChange={(e) => setRequirements({
                          ...requirements,
                          [key]: e.target.checked
                        })}
                        className="w-5 h-5 text-purple-600 rounded focus:ring-purple-500"
                        disabled={analyzing}
                      />
                      <span className="text-gray-700">
                        {key.replace('needs', 'Needs ')}
                      </span>
                    </label>
                  ))}
                </div>
              </div>

              {/* Analyze Button */}
              <button
                onClick={handleAnalyze}
                disabled={analyzing || !geminiAvailable || !description.trim()}
                className="w-full bg-gradient-to-r from-purple-600 to-indigo-600 text-white py-4 px-6 rounded-lg font-semibold text-lg hover:from-purple-700 hover:to-indigo-700 disabled:opacity-50 disabled:cursor-not-allowed transition-all transform hover:scale-105 shadow-lg"
              >
                {analyzing ? (
                  <span className="flex items-center justify-center">
                    <svg className="animate-spin h-5 w-5 mr-3" viewBox="0 0 24 24">
                      <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" fill="none" />
                      <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z" />
                    </svg>
                    Analyzing with Gemini AI...
                  </span>
                ) : (
                  '✨ Analyze Project with Gemini'
                )}
              </button>
            </div>
          )}

          {/* Step 2: Analysis Results */}
          {analysisResult && !downloadUrl && (
            <div className="space-y-6">
              <div className="bg-gradient-to-r from-purple-50 to-indigo-50 p-6 rounded-lg border-2 border-purple-200">
                <h2 className="text-2xl font-bold text-gray-900 mb-4">
                  🎯 Analysis Complete
                </h2>
                <p className="text-gray-700 mb-4">{analysisResult.analysis}</p>
                
                {/* Suggested Agents */}
                <div className="space-y-3 mb-6">
                  <h3 className="text-lg font-semibold text-gray-900">
                    Selected AI Agents:
                  </h3>
                  {analysisResult.suggested_agents.map((agent) => (
                    <div key={agent.agent_id} className="bg-white p-4 rounded-lg shadow">
                      <div className="flex justify-between items-start">
                        <div>
                          <h4 className="font-semibold text-gray-900">{agent.agent_name}</h4>
                          <p className="text-sm text-gray-600 mt-1">{agent.reason}</p>
                        </div>
                        <span className="text-xs bg-purple-100 text-purple-800 px-2 py-1 rounded">
                          ~{agent.estimated_tokens} tokens
                        </span>
                      </div>
                    </div>
                  ))}
                </div>

                {/* Cost Estimate */}
                <div className="bg-white p-4 rounded-lg border-2 border-purple-300">
                  <div className="flex justify-between items-center">
                    <span className="font-semibold text-gray-900">Estimated Cost:</span>
                    <span className="text-2xl font-bold text-purple-600">
                      ${analysisResult.total_estimated_cost.toFixed(2)}
                    </span>
                  </div>
                  <div className="text-sm text-gray-600 mt-2">
                    Total tokens: ~{analysisResult.total_estimated_tokens.toLocaleString()}
                  </div>
                </div>
              </div>

              {/* Action Buttons */}
              <div className="flex gap-4">
                <button
                  onClick={handleCreateProject}
                  disabled={creating}
                  className="flex-1 bg-gradient-to-r from-green-600 to-emerald-600 text-white py-4 px-6 rounded-lg font-semibold text-lg hover:from-green-700 hover:to-emerald-700 disabled:opacity-50 disabled:cursor-not-allowed transition-all transform hover:scale-105 shadow-lg"
                >
                  {creating ? (
                    <span className="flex items-center justify-center">
                      <svg className="animate-spin h-5 w-5 mr-3" viewBox="0 0 24 24">
                        <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" fill="none" />
                        <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z" />
                      </svg>
                      Generating Code...
                    </span>
                  ) : (
                    '🚀 Create Project'
                  )}
                </button>
                <button
                  onClick={handleReset}
                  className="px-6 py-4 border-2 border-gray-300 text-gray-700 rounded-lg font-semibold hover:bg-gray-50 transition-all"
                >
                  ← Start Over
                </button>
              </div>
            </div>
          )}

          {/* Step 3: Download Ready */}
          {downloadUrl && (
            <div className="text-center space-y-6">
              <div className="bg-gradient-to-r from-green-50 to-emerald-50 p-8 rounded-lg border-2 border-green-200">
                <div className="text-6xl mb-4">🎉</div>
                <h2 className="text-3xl font-bold text-gray-900 mb-2">
                  Project Ready!
                </h2>
                <p className="text-gray-700 mb-6">
                  Your code has been generated successfully
                </p>
                
                <button
                  onClick={handleDownload}
                  className="bg-gradient-to-r from-green-600 to-emerald-600 text-white py-4 px-8 rounded-lg font-semibold text-lg hover:from-green-700 hover:to-emerald-700 transition-all transform hover:scale-105 shadow-lg inline-flex items-center"
                >
                  <svg className="w-6 h-6 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
                  </svg>
                  Download Project ZIP
                </button>
              </div>

              <button
                onClick={handleReset}
                className="px-6 py-3 border-2 border-gray-300 text-gray-700 rounded-lg font-semibold hover:bg-gray-50 transition-all"
              >
                Create Another Project
              </button>
            </div>
          )}

          {/* Error Display */}
          {error && (
            <div className="mt-6 bg-red-50 border-2 border-red-200 rounded-lg p-4">
              <div className="flex items-start">
                <svg className="w-6 h-6 text-red-600 mr-3 flex-shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 8v4m0 4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                </svg>
                <div>
                  <h3 className="font-semibold text-red-900">Error</h3>
                  <p className="text-red-700 mt-1">{error}</p>
                </div>
              </div>
            </div>
          )}
        </div>

        {/* Footer */}
        <footer className="text-center mt-8 text-gray-600">
          <p>Powered by Gemini AI • BOB Orchestrator • Made with ❤️</p>
        </footer>
      </div>
    </div>
  );
}

// Made with Bob
